/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientUI;

import client.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Admin
 */
public class ChatUI extends javax.swing.JFrame implements KeyListener {
    
    private User user;
    private String curFriendName;
    private String curGroupName;
        
    /**
     * Creates new form chatGUI
     */
    private DefaultListModel listOnl = new DefaultListModel();
    private DefaultListModel listOff = new DefaultListModel();
    private DefaultListModel listGroup = new DefaultListModel();
    StyledDocument doc;
    SimpleAttributeSet messageAlign;
    
    public ChatUI() {
        initComponents();
        initSetting();
    }
    
    public ChatUI(User user) {
        this.user = user;
        curFriendName = "";
        curGroupName = "";
        initComponents();
        initSetting();
    }        
    
    private void initSetting() {
        //Create list for online and offline friends
        offlineList.setModel(listOff);
        offlineList.setEnabled(false);
        
        onlineList.setModel(listOnl);
        groupList.setModel(listGroup);
  
        mess.addActionListener(typeMessage);
        findUser.addActionListener(newChat);
        doc = jTextPane1.getStyledDocument();
        messageAlign= new SimpleAttributeSet();
        JScrollPane   scroll = new JScrollPane();
        jTextPane1.add(scroll); 
        jTextPane1.setEditable(false);
        
        jLabel1.setText("My name is " + user.getUserName() + "!");
        
        //  TODO
        // initial add online offline friends
        friendClassify();
        
        user.setChatUI(this);
        user.start();
        user.getRequestServer().setTypeOfRequest(6);
    }

    
    public String getCurFriendName() {
        return curFriendName;
    }
    
    public String getCurGroupName() {
        return curGroupName;
    }

    public void setCurFriendName(String curFriendName) {
        this.curFriendName = curFriendName;
    }

    public void setCurGroupName(String curGroupName) {
        this.curGroupName = curGroupName;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mess = new javax.swing.JTextField();
        sendMessButton = new javax.swing.JButton();
        sendFileButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        offlineList = new javax.swing.JList<>();
        findUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        findButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        clearButton = new javax.swing.JButton();
        groupButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backicon.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F1");

        mess.setToolTipText("Type messages here");
        mess.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messFocusLost(evt);
            }
        });

        sendMessButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sendicon.png"))); // NOI18N
        sendMessButton.setText("Send");
        sendMessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessButtonActionPerformed(evt);
            }
        });

        sendFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attachicon.png"))); // NOI18N
        sendFileButton.setText("Attach");
        sendFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileButtonActionPerformed(evt);
            }
        });

        offlineList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(offlineList);

        findUser.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        findUser.setToolTipText("Enter friend name to chat");
        findUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                findUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                findUserFocusLost(evt);
            }
        });

        jLabel2.setText("Online");

        findButton.setText("Chat");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        onlineList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        onlineList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        onlineList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onlineListMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onlineListMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(onlineList);

        jLabel3.setText("Offine");

        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane1.setKeymap(null);
        jScrollPane4.setViewportView(jTextPane1);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        groupButton.setText("Group");
        groupButton.setToolTipText("");
        groupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButtonActionPerformed(evt);
            }
        });

        groupList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        groupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                groupListMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(groupList);

        jLabel4.setText("Group");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(sendMessButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sendFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(findUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(findButton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(groupButton)
                                .addGap(18, 18, 18)
                                .addComponent(clearButton)))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(clearButton)
                            .addComponent(groupButton))
                        .addGap(5, 5, 5)))
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendMessButton)
                            .addComponent(sendFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(findButton)
                            .addComponent(findUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // type = 1: peer chat - type = 2: group chat
    public void newMess(String name, int type) {
        if (type == 1) {
            int size = listOnl.getSize();
            for (int i = 0; i < size; i++) {
                // System.out.println(listOnl.getElementAt(i));
                if (listOnl.getElementAt(i).equals(name)) {
                    //System.out.println("OK");
                    listOnl.setElementAt("o\t" + name, i);
                }
            }
        } else if (type == 2) {
            int size = listGroup.getSize();
            for (int i = 0; i < size; i++) {
                // System.out.println(listGroup.getElementAt(i));
                if (listGroup.getElementAt(i).equals(name)) {
                    //System.out.println("OK");
                    listGroup.setElementAt("o\t" + name, i);
                }
            }
        }
        
        
    }
    
    //
    public void friendClassify() {
        if (!user.getFriendList().isEmpty()) {
            int numOfFriends = user.getFriendList().size();

            for (int i = 0; i < numOfFriends; i++) {
                Friend friend = (new ArrayList<>(user.getFriendList().values())).get(i);
               
                if (friend.getStatus() == 1) {
                    addName(friend.getName(), 1);
                } else {
                    addName(friend.getName(), 0);
                }
            }
        }
    }
    
    // Display the messages communicated with friend
    public void displayMess(String friendName) {
        try {
            doc.remove(0, doc.getLength());
        } catch(BadLocationException e) { 
            System.out.println(e);
        }
        
        // get message record with friend
        //MessRecord messRecord = user.getFriendList().get(friendName).getMessRecord();
        //MessRecord messRecord = user.getMessRecordList().get(friend);
        ArrayList<String> messRecord = user.getFriendList().get(friendName).getMessRecord();
        
        for (int i = 0; i < messRecord.size(); i++) {
            String message = messRecord.get(i);
            if (message.charAt(0) == '1') {
                ownerChatMessage(message.substring(1));
            } else {
                friendChatMessage(message.substring(1));
            }
        }
    } 
    
    // Display the messages communicated with friends in group chat
    public void displayGroupMess(String groupName) {
        try {
            doc.remove(0, doc.getLength());
        } catch(BadLocationException e) { 
            System.out.println(e);
        }
        
        // get message record with friends in group chat
        GroupChat groupChat = user.getGroupChatList().get(groupName);
        
        for (int i = 0; i < groupChat.getMessList().size(); i++) {
            String message = groupChat.getMessList().get(i);
            if (message.charAt(0) == '1') {
                ownerChatMessage(message.substring(1));
            } else {
                friendChatMessage(message.substring(1));
            }
        }
    } 
    
    
    // Send message to other clients
    public void ownerChat() {
        if (    !mess.getText().equals("") && 
                !curFriendName.equals("")) {
            // get friend's info
            Friend friend = (user.getFriendList()).get(curFriendName);
            //create a thread to send message
            new SendMess(user, friend, mess.getText(), 1).start();
            
            mess.setText("");
        } else if (    !mess.getText().equals("") && 
                       !curGroupName.equals("")) {
            // get group chat info
            GroupChat groupChat = (user.getGroupChatList()).get(curGroupName);
            groupChat.sendGroupMess(user, mess.getText());
            
            mess.setText("");
        } 
    }
     
    private void ownerChatMessage(String message) {
        StyleConstants.setAlignment(messageAlign, StyleConstants.ALIGN_RIGHT);
        try
        {
            int length = doc.getLength();
            doc.insertString(doc.getLength(), "\n" + message, null);
            doc.setParagraphAttributes(length+3, 1, messageAlign, false);
        }
        catch(BadLocationException e) { System.out.println(e);}
    } 
    
    
    private void friendChatMessage(String message) {
        StyleConstants.setAlignment(messageAlign, StyleConstants.ALIGN_LEFT);
        try
        {
            int length = doc.getLength();
            doc.insertString(doc.getLength(),"\n" + message, null);
            doc.setParagraphAttributes(length+3, 1, messageAlign, false);
        }
        catch(BadLocationException e) { System.out.println(e);}
    }
    
    
    private int checkExistance(String name, DefaultListModel friendlist) {
        int size = friendlist.getSize();
        for (int i =0; i < size; i++){
            if (friendlist.getElementAt(i).equals(name)) 
                return i;
        }
        return -1;
    }
    
    // ***** selectedList = 1 online friendlist, 0  offline friend list *****
    // Add a new name to list
    public void addName(String name, int selectedList) {
        if (selectedList == 0){
            if (checkExistance(name, listOff) == -1){
                listOff.addElement(name);
            }
        }  
        
        if (selectedList == 1){
            if (checkExistance(name, listOnl) == -1){
                listOnl.addElement(name);
            }
        } 
    } 
    // Remove a name from list
    public void removeName(String name, int selectedList) {
        if (selectedList == 0){
            int pos = checkExistance(name, listOff);
            if ( pos != -1){
                listOff.remove(pos);
            }
        }  
        
        if (selectedList == 1){
            int pos = checkExistance(name, listOnl);
            if ( pos != -1){
                listOnl.remove(pos);
            }
        }
    } 
    
    
    // type = 1: add group to list --- type = 2: remove group from list
    public void updateGroup(String groupName, int type) {
        if (type == 1) {
            listGroup.addElement(groupName);
        } else if (type == 0) {
            listGroup.removeElement(groupName);
        }
    }
      
    private void beginChat() {
        String getName = findUser.getText().trim();
        
        if (getName.equals(user.getUserName())) {
            // your username
            JOptionPane.showMessageDialog(null, "It is YOU!");
        } else if (listGroup.contains(getName)) {
            // group chatting
            jLabel1.setText("Group Chat " + getName);
            curFriendName = "";
            curGroupName = getName; 
            displayGroupMess(getName);
        } else if (checkExistance(getName,listOnl) != -1) {
            // friend is online
            jLabel1.setText("You are chatting with " + getName); 
            curFriendName = getName;
            curGroupName = "";
            displayMess(getName);
        } else if (checkExistance(getName, listOff) != -1 ) {
            // friend is offline
            JOptionPane.showMessageDialog(null, "Your friend is offline");
        } else { 
            // not your friend
            user.setUserNameAdding(getName);
            user.requestToServer("find");
        }
    }
    
    
    public void updateTextArea() {
        jLabel1.setText("My name is " + user.getUserName() + "!");
        curFriendName = "";
        curGroupName = "";
        try {
            doc.remove(0, doc.getLength());
        } catch(BadLocationException e) { 
            System.out.println(e);
        }
    }
 
    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        beginChat();
    }//GEN-LAST:event_findButtonActionPerformed

    private void messFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messFocusGained
        // TODO add your handling code here:
        if (mess.getText().equals("Type here"))
            mess.setText("");
    }//GEN-LAST:event_messFocusGained

    private void messFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messFocusLost
        // TODO add your handling code here:
        if (mess.getText().equals("")){
            //jTextField1.setText("Type here");
        }
    }//GEN-LAST:event_messFocusLost

    private void findUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_findUserFocusGained
        // TODO add your handling code here:
        if (findUser.getText().equals("Enter name...")){
            findUser.setText("");
        } 
    }//GEN-LAST:event_findUserFocusGained

    private void findUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_findUserFocusLost
        // TODO add your handling code here:
        if (!findUser.getText().equals("Enter name ...")){
//            findUser.setText("Enter name...");
              findUser.setText("");
        }
    }//GEN-LAST:event_findUserFocusLost

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        
        user.requestToServer("logout");
        
        if (!user.getFriendList().isEmpty()) {
            int numOfFriends = user.getFriendList().size();
            
            for (int i = 0; i < numOfFriends; i++) {
                Friend friend = (new ArrayList<>(user.getFriendList().values())).get(i);
               
                if (friend.getStatus() == 1) {
                    //create a thread to send message
                    new SendMess(user, friend, "off", 5).start();
                }
            }
        }
        
        if (!user.getGroupChatList().isEmpty()) {

            for (int i = 0; i < user.getGroupChatList().size(); i++) {
                GroupChat groupChat = (new ArrayList<>(user.getGroupChatList().values())).get(i);
               
                for (int j = 0; j < groupChat.getMemberList().size(); j++) {
                    Friend friend = (new ArrayList<>(groupChat.getMemberList().values())).get(j);
                
                    new SendMess(user, friend, "off", 5).start();
                }
            }
        }
        // close the receiver socket
        try {
            user.getServerSocket().close();
        } catch (IOException ex) {
            Logger.getLogger(ChatUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LoginUI newUser = new LoginUI();
        newUser.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void sendMessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessButtonActionPerformed
        if (!jLabel1.getText().contains(user.getUserName())) {
            ownerChat();    
        }
    }//GEN-LAST:event_sendMessButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        updateTextArea();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void onlineListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineListMouseClicked
        // TODO add your handling code here:
        onlineList.clearSelection();
    }//GEN-LAST:event_onlineListMouseClicked

    private void sendFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileButtonActionPerformed
        // TODO add your handling code here:
        if (jLabel1.getText().contains(curFriendName)) {
            FileUI fileUI = new FileUI(user, user.getFriendList().get(curFriendName));
            fileUI.setVisible(true);    
        }
    }//GEN-LAST:event_sendFileButtonActionPerformed

    private void onlineListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineListMousePressed
        // TODO add your handling code here:
        if (onlineList.getSelectedValue().contains("o\t")) {
            listOnl.setElementAt(onlineList.getSelectedValue().substring(2), 
                    onlineList.getSelectedIndex());
        }
        jLabel1.setText("You are chatting with " + onlineList.getSelectedValue());
        curGroupName = "";
        curFriendName = onlineList.getSelectedValue();
        onlineList.clearSelection();
        
        displayMess(curFriendName);
    }//GEN-LAST:event_onlineListMousePressed

    private void groupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButtonActionPerformed
        // TODO add your handling code here:
        GroupChooseUI groupChooseUI = new GroupChooseUI(user);
        groupChooseUI.setVisible(true);
    }//GEN-LAST:event_groupButtonActionPerformed

    private void groupListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupListMousePressed
        // TODO add your handling code here:
        if (groupList.getSelectedValue().contains("o\t")) {
            listGroup.setElementAt(groupList.getSelectedValue().substring(2), 
                    groupList.getSelectedIndex());
        }
        jLabel1.setText("Group Chat " + groupList.getSelectedValue());
        curFriendName = "";
        curGroupName = groupList.getSelectedValue(); 
        groupList.clearSelection();
        
        displayGroupMess(curGroupName);
    }//GEN-LAST:event_groupListMousePressed

    
    Action typeMessage = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            ownerChat();
        }
    };
    
    Action newChat = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //System.out.println("some action");
            beginChat();
        }
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChatUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField findUser;
    private javax.swing.JButton groupButton;
    private javax.swing.JList<String> groupList;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField mess;
    private javax.swing.JList<String> offlineList;
    private javax.swing.JList<String> onlineList;
    private javax.swing.JButton sendFileButton;
    private javax.swing.JButton sendMessButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
